name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: FIP14v5
  comment: FIFA 14 Patch 2023
  url: https://drive.google.com/drive/folders/1SVK7yW-__rUAdwEZLaNbY4l_oLmM9zxQ
  file_name: 0-FIP14v500-BETA.rar
  piece_size: 2^19
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
